feature: support tunnel preview table records
aliyun/aliyun-odps-go-sdk pull request #12
Opened 2023-10-09 03:17 UTC by yyMoming

2023-10-09 03:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/aliyun-odps-go-sdk?pullRequest=12) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/aliyun-odps-go-sdk?pullRequest=12) before we can accept your contribution.<br/><hr/>**wenyu.ywm** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/aliyun-odps-go-sdk?pullRequest=12) it.</sub>

2024-10-30 09:05 UTC, dingxin-tech commented
LGTM，我居然能push你的分支 @yyMoming

2024-10-30 09:26 UTC, fetchadd requested changes

2024-10-30 09:26 UTC, fetchadd commented on odps/tunnel/arrow_stream_record_reader.go
> +func (ar *ArrowStreamRecordReader) Iterator(f func(array.Record, error)) {
这种接口之前有设计上的缺陷，应该把错误作为Iterator的返回值，遇到错误中断iterator。部分iterator已经改了

2024-10-30 09:26 UTC, fetchadd commented on odps/tunnel/tunnel.go
> +	//
这种无用注释都去掉

2024-10-30 09:26 UTC, fetchadd commented on odps/tunnel/tunnel.go
> +	limit int64, opt ...Option) (*http.Response, error) {
这个接口为什么要返回http reponse

2024-10-30 09:26 UTC, fetchadd commented on odps/tunnel/arrow_stream_record_reader.go
> +type ArrowStreamRecordReader struct {
名字应该叫RecordArrowStreamReader, 包括.go文件名

2024-10-30 09:26 UTC, fetchadd commented on odps/tunnel/arrow_stream_record_reader.go
> +func (ar *ArrowStreamRecordReader) HttpRes() *http.Response {
这个方法非必要不透出

2024-10-30 09:26 UTC, fetchadd commented on odps/tunnel/tunnel.go
> +func (t *Tunnel) ReadTable(table *odps.Table, partition string, limit int64) (*ArrowStreamRecordReader, error) {
根据返回值，这个方面名字应该OpenRecordArrowStreamReader

2024-10-30 09:26 UTC, fetchadd commented on odps/tableschema/table_schema.go
> +func (schema *TableSchema) ToArrowSchema(opt ...ToArrowSchemaOption) *arrow.Schema {
这个方法原理是给arrow tunnel用，arrow tunnel没有实际客户。如果要扩展参数，用类似UploadSession配置的方式

2024-10-30 09:26 UTC, fetchadd commented on odps/tableschema/table_schema.go
> +func (schema *TableSchema) ToArrowSchema(opt ...ToArrowSchemaOption) *arrow.Schema {
扩展参数应该可以和arrow_util.go里的 TypeConvertOption 用一个吧，看一下 TypeConvertOption 名字是否合适

2024-10-30 09:26 UTC, fetchadd commented on odps/tunnel/tunnel.go
> +	limit int64, opt ...Option) (*http.Response, error) {
这个方法用来干嘛的，需要暴漏吗

2024-10-30 09:36 UTC, dingxin-tech commented on odps/tunnel/arrow_stream_record_reader.go
> +type ArrowStreamRecordReader struct {
和 Java SDK 一致吧，别起名了

2024-10-30 09:36 UTC, dingxin-tech commented on odps/tunnel/tunnel.go
> +func (t *Tunnel) ReadTable(table *odps.Table, partition string, limit int64) (*ArrowStreamRecordReader, error) {
OpenRecordReader 吧，Arrow Stream 对用户屏蔽

2024-10-30 09:49 UTC, fetchadd commented on odps/tunnel/arrow_stream_record_reader.go
> +type ArrowStreamRecordReader struct {
ArrowStreamRecordReader 不讲逻辑，不跟

2024-11-01 10:06 UTC, fetchadd requested changes

2024-11-01 10:06 UTC, fetchadd commented on odps/tunnel/tunnel.go
> +// Preview table records from table tunnel, max 10000 rows
这里partition格式是什么样的，是p1=xx,p2=sss 还是p1=xx/p2=sss，要求用后者。如果api用的是前者，转换一下

2024-11-01 10:06 UTC, fetchadd commented on odps/tunnel/example_tunnel_test.go
> +func ExampleTunnel_Preview() {
给一个分区表的示例

2024-11-01 10:06 UTC, fetchadd commented on odps/data/decimal.go
> +const ParseFromValue = "__ParseFromValue__"
这个变量改成私有的

2024-11-05 08:42 UTC, fetchadd requested changes
更新一下官网文档

2024-11-05 08:42 UTC, fetchadd commented on odps/tunnel/example_tunnel_test.go
> +	records, err := tunnelIns.Preview(ts, "", 10)
分区表不加分区的话preview可以返回值？

2024-11-05 08:48 UTC, merged