feat: add support for timestamp_ntz data type
aliyun/aliyun-odps-go-sdk pull request #32
Opened 2024-10-18 06:50 UTC by robin11

add support for timestamp_ntz data type

2024-10-18 06:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/aliyun-odps-go-sdk?pullRequest=32) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/aliyun-odps-go-sdk?pullRequest=32) before we can accept your contribution.<br/><hr/>**haochuan.lj** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/aliyun-odps-go-sdk?pullRequest=32) it.</sub>

2024-10-18 07:05 UTC, dingxin-tech commented
LGTM

2024-10-23 01:50 UTC, fetchadd requested changes
修改examples中所有all_types_demo示例，添加timestamp_ntz

要改的示例:
1. sdk/create_table_use_table_schema
2. tunnel/upload_data_use_protoc
3. tunnel/download_data_use_protoc
4. upload_data_use_stream_tunnel
5. sql/create_table
6. sql/select_data_1

2024-10-30 02:08 UTC, fetchadd approved these changes
LGTM

2024-10-30 02:09 UTC, merged