feat: 新增 Table Creator 用来执行建表操作
aliyun/aliyun-odps-go-sdk pull request #34
Opened 2024-10-23 02:12 UTC by dingxin-tech

2024-10-29 02:02 UTC, fetchadd requested changes

2024-10-29 02:02 UTC, fetchadd commented on odps/tables.go
> +func NewTableCreator(odps *Odps, identifier *TableIdentifier, dataColumn []tableschema.Column) *TableCreator {
1. 这个应该是Table.Create的参数，他本身不需要Create方法。
2. identfifier应该明确展开为projectName, schemaName, tableName, schemaName == ""时为二层模型

2024-10-29 05:37 UTC, dingxin-tech commented on odps/tables.go
> +type TableCreator struct {
尽管同样使用Builder模式，TableBuilder 可能引发歧义。Builder 模式通常用于替代一个类的构造方法，TableBuilder 会被认为是 Table 类的构造器，而非 Table 的创建器。

2024-10-29 05:43 UTC, dingxin-tech commented on odps/tables.go
> +func NewTableCreator(odps *Odps, identifier *TableIdentifier, dataColumn []tableschema.Column) *TableCreator {
1. TableCreator 使用 Builder 模式，使用户可以进行链式调用。作为 Tables.Create 方法的参数，提高了使用成本。
2. TableIdentifier 类的目的是为了在这个场景下替代 projectName, schemaName, tableName 的指代
    因为对于二层模型的用户，方法使用 (projectName, "", tableName) 是十分奇怪的。

2024-10-29 05:50 UTC, dingxin-tech commented on odps/identifier.go
> +func TableId(option ...string) *TableIdentifier {
已完善文档

2024-10-30 03:35 UTC, closed without merging

2024-10-30 03:35 UTC, dingxin-tech commented
鉴于 review 意见，此 PR 进展推迟